# This file is identical to ASR_train_config.yaml, but with a smaller sample size for testing purposes
# Project settings
project: "Kinyarwanda-ASR"
output_dir: "outputs/baseline"
seed: 42

# Model settings
pretrained_model: "facebook/w2v-bert-2.0"
freeze_feature_encoder: false

# Training settings
batch_size: 4
gradient_accumulation_steps: 16
num_epochs: 25
max_steps: 50000
learning_rate: 0.00005
warmup_ratio: 0.1
fp16: true
gradient_checkpointing: true
save_steps: 1000
eval_steps: 1000
logging_steps: 50
save_total_limit: 2

# Data settings
use_custom_dataset: true
dataset_path: "./kinyarwanda_asr_dataset"

training_split: "train"
validation_split: "validation"
test_split: "test"

# Data preprocessing settings
sample: true
sample_size: 1000 # not used if sample is false
include_apstrophes: true

