# Project settings
project: "Kinyarwanda-ASR"
output_dir: "inprogress/baseline"
seed: 42

# Model settings
pretrained_model: "facebook/w2v-bert-2.0"
freeze_feature_encoder: true

# Training settings
batch_size: 4
gradient_accumulation_steps: 8
num_epochs: 25
max_steps: 42000
learning_rate: 0.00007 #0.00005 #0.00005
warmup_ratio: 0.05
fp16: true
gradient_checkpointing: true
save_steps: 800
eval_steps: 800
logging_steps: 5
save_total_limit: 2

# Data settings
# if use_custom_dataset is true, then dataset_path is the path to the custom dataset on disk
# if use_custom_dataset is false, then dataset_path is the dataset repo name on the HF hub
use_custom_dataset: false
# if from HF hub, use the repo name badrex/kinyarwanda-speech-500h
dataset_path: "badrex/kinyarwanda-speech-1000h" #"./kinyarwanda-ASR/kinyarwanda_asr_dataset" 
train_split: "train"
eval_split: "validation"

# Data sampling settings (for debugging purposes)
sample: false
sample_size: 1000 # not used if sample is false
#include_apstrophes: true
